package dev.bogdanzurac.marp.buildplugins

object projects {
    const val appElgoog = "app-elgoog"
    const val core = "core"
    const val coreAuth = "core-auth"
    const val coreData = "core-data"
    const val coreDb = "core-db"
    const val corePrompts = "core-prompts"
    const val coreNavigation = "core-navigation"
    const val coreServices = "core-services"
    const val coreUi = "core-ui"
    const val coreWs = "core-ws"
    const val featureCryptoData = "feature-crypto-data"
    const val featureCryptoDomain = "feature-crypto-domain"
    const val featureCryptoUi = "feature-crypto-ui"
    const val featureCryptoUiCommon = "feature-crypto-ui-common"
    const val featureWeatherData = "feature-weather-data"
    const val featureWeatherDomain = "feature-weather-domain"
    const val featureWeatherUi = "feature-weather-ui"
    const val libDbFirebase = "lib-db-firebase"
    const val libFlaggingFirebase = "lib-flagging-firebase"
    const val libServicesGoogle = "lib-services-google"
    const val libServicesHuawei = "lib-services-huawei"
    const val libTrackingFirebase = "lib-tracking-firebase"
}